### Submit Suppliers
GET http://localhost:4004/odata/v4/hc450-officesupplies/Suppliers?$top=2

### Browse Products
GET http://localhost:4004/odata/v4/hc450-officesupplies/Products?$top=2

### Browse Products - Product,Identifier ,Price
GET http://localhost:4004/odata/v4/hc450-officesupplies/Products?
&$select=identifier,price

### Submit Products
POST http://localhost:4004/odata/v4/hc450-officesupplies/Products
Content-Type: application/json

{"ID":"a9fe4b01-ccd3-4369-821c-291a7552dffc" ,
  "title" : "Test Zakaria 2"
}